version: '3.8'

services:
  backend:
    image: stavrmoris777/sberlab-backend:latest
    container_name: sberlab_backend
    ports:
      - "8000:8000"
    volumes:
      - media_volume:/app/media
      - db_volume:/app/db.sqlite3  # Чтобы база сохранялась (опционально)
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: stavrmoris777/sberlab-frontend:latest
    container_name: sberlab_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  media_volume:
  db_volume:
