# Generated by Django 5.2.10 on 2026-01-30 08:45

import ckeditor.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('mentor', 'Ментор (Сбер)'), ('teacher', 'Преподаватель (НГУ)'), ('hr', 'HR')], default='student', max_length=20)),
                ('fio', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('group_number', models.CharField(blank=True, max_length=20)),
                ('gpa', models.FloatField(default=0.0, verbose_name='Средний балл')),
                ('is_verified', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('about', models.TextField(blank=True)),
                ('tech_stack', models.CharField(blank=True, max_length=500)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('github', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', ckeditor.fields.RichTextField(blank=True)),
                ('tech_stack', models.CharField(max_length=200)),
                ('max_students', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('open', 'Набор открыт'), ('in_progress', 'В работе'), ('done', 'Завершен')], default='open', max_length=20)),
                ('complexity', models.CharField(choices=[('easy', '🟢 Легкий'), ('medium', '🟡 Средний'), ('hard', '🔴 Сложный')], default='medium', max_length=10)),
                ('urgency', models.CharField(choices=[('low', 'Спокойно'), ('medium', 'Срочно'), ('high', '🔥 Горит')], default='medium', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_nda_required', models.BooleanField(default=False, verbose_name='Требуется NDA')),
                ('is_diploma_allowed', models.BooleanField(default=False, verbose_name='Можно как диплом')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('mentors', models.ManyToManyField(related_name='mentored_projects', to=settings.AUTH_USER_MODEL, verbose_name='Менторы')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Заявка подана'), ('accepted', 'Принят в команду'), ('rejected', 'Отклонен'), ('completed', 'Успешно завершил')], default='pending', max_length=20)),
                ('cover_letter', models.TextField(blank=True, verbose_name='Мотивационное письмо')),
                ('is_diploma_request', models.BooleanField(default=False, verbose_name='Хочу как диплом')),
                ('is_nda_signed', models.BooleanField(default=False, verbose_name='NDA Подписан')),
                ('mentor_review', models.TextField(blank=True, verbose_name='Отзыв ментора')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Оценка (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
