# Generated by Django 6.0.1 on 2026-01-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='projects/docs/', verbose_name='ТЗ или доп. материалы'),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='Подробное ТЗ'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео (YouTube/Drive)'),
        ),
    ]
