# Generated by Django 6.0.1 on 2026-01-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub / Portfolio'),
        ),
        migrations.AddField(
            model_name='user',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=500, verbose_name='Стек (Python, React...)'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram (@user)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.CharField(blank=True, max_length=255, verbose_name='Другие контакты'),
        ),
    ]
