# Generated by Django 6.0.1 on 2026-01-29 07:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_avatar_user_github_user_tech_stack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='complexity',
            field=models.CharField(choices=[('easy', '🟢 Легкий'), ('medium', '🟡 Средний'), ('hard', '🔴 Сложный')], default='medium', max_length=10, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн (пусто = бессрочно)'),
        ),
        migrations.AddField(
            model_name='project',
            name='urgency',
            field=models.CharField(choices=[('low', 'Спокойно'), ('medium', 'Срочно'), ('high', '🔥 Горит')], default='medium', max_length=10, verbose_name='Срочность'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Полное ТЗ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_students',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на YouTube'),
        ),
    ]
